[package]
name = "mapbox_vector_tile"
version = "0.1.0"
authors = ["Rory McCann <rory@technomancy.org>"]

[dependencies]
geo = { git = "file:///home/rory/code/rust/rust-geo", branch = "rory-everything" }
protobuf = "*"
flate2 = { version = "0.2", features = ["zlib"] }
slippy-map-tiles = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
geojson = "*"
